config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  # get 'books/index'
  #
  # get 'books/new'
  #
  # get 'books/create'
  #
  # get 'books/edit'
  #
  # get 'books/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :books
  root 'books#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews 
  validates :name, presence: true, length: { maximum: 20}
  validates :price, presence: true
  validates :publish, presence: true
  validates :publish_date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: [:show, :edit, :update, :destory]


  def show
  end

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      flash.now[:alert] = @book.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to "/books/#{@book.id}"
    else
      flash.now[:alert] = @book.errors.full_messages
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

    def book_params
      params.require(:book).permit(:name, :price, :publish, :publish_date)
    end

    def set_book
      @book = Book.find(params[:id])
    end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to book_path(@review.book), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to book_path(@review.book), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:book_id, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_new_review.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.hidden_field :book_id, id: :review_book_id %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :review_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>書籍編集フォーム</h1>

<% if flash["alert"].present? %>
  <% flash["alert"].each do |value| %>
    <%= content_tag(:div, value) %>
  <% end %>
<% end %>

<%= form_with model: @book, local: true do |form| %>

<p>
  書籍名：<br>
  <%= form.text_field :name %>
</p>

<p>
  価格：<br>
  <%= form.number_field :price %>
</p>

<p>
  出版社：<br>
  <%= form.text_field :publish %>
</p>

<p>
  刊行日：<br>
  <%= form.date_field :publish_date %>
</p>

<%= form.submit "更新" %>

<% end %>

app/views/books/index.html.erb
<h1>書籍一覧</h1>
<ul>
  <% @books.each do |book| %>
    <li><%= link_to book.name, book_path(book) %></li>
    <% end %>
</ul>

<%= link_to '登録する', new_book_path %>

app/views/books/new.html.erb
<h1>書籍登録フォーム</h1>

<% if flash["alert"].present? %>
  <% flash["alert"].each do |value| %>
    <%= content_tag(:div, value) %>
  <% end %>
<% end %>

<%= form_with model: @book, local: true do |form| %>

<p>
  書籍名：<br>
  <%= form.text_field :name %>
</p>

<p>
  価格：<br>
  <%= form.number_field :price %>
</p>

<p>
  出版社：<br>
  <%= form.text_field :publish %>
</p>

<p>
  刊行日：<br>
  <%= form.date_field :publish_date %>
</p>

<%= form.submit "登録" %>

<% end %>

app/views/books/show.html.erb
<p>
    <b>商品名：<%= @book.name %></b>
</p>

<p>
    <b>商品名：<%= @book.price %></b>
</p>

<p>
    <b>商品名：<%= @book.publish %></b>
</p>

<p>
    <b>商品名：<%= @book.publish_date %></b>
</p>

<h3>レビュー一覧</h3>
<ul>
  <% @book.reviews.each do |review| %>
    <li>
      <%= review.body %> - <%= review.created_at %>
      <%= link_to "削除", review_path(review), method: :delete %>
        <!-- method:を指定しないとgetになる。 -->
    </li>
  <% end %>
</ul>

<h3>投稿</h3>
<%= render partial: 'new_review', locals: { review: @book.reviews.new } %>
  <!--  -->
<p>
<%= link_to '編集', edit_book_path(@book) %>
<%= link_to '削除', book_path(@book), method: :delete %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookShelf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.number_field :book_id, id: :review_book_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :review_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Book</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.book_id %></td>
        <td><%= review.body %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @review.book_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @review.body %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>